site_name: Switchless Docs
theme:
    name: null
    custom_dir: 'docs/custom_theme2/'
    sidebars: 
        - about
        - search
extra:
    logo: files/switchless_docs_logo.png
    sidebars:
        - about
        - navigation
    homepage_sidebars:
        - about
        - navigation
plugins:
    - roamlinks
nav:
    - Getting started:
        - Getting started: 'getting_started/index.md'
        - Setup Web App: 'getting_started/setup_web_app.md'
    - Auth:
        - Bearer auth: 'auth/bearer_auth.md'
    - Stack:
        - Logging : 'stack/logging.md'
        - Blueprint API : 'stack/blueprint_apis.md'
        - Mailgun: 'stack/mailgun.md'
        - Metabase: 'stack/metabase.md'
        - Mk Docs: 'stack/mkdocs.md'
        - Postgresql: 'stack/postgresql.md'
        # - Sendgrid: 'stack/sendgrid.md'
        - Switchless cli : 'stack/switchless-cli.md'
        - Sentry : 'stack/sentry.md'
        - Wordpress: 'stack/wordpress.md'
    - Patterns:
        - Tables: 'patterns/tables.md'
        - Steps and stages: 'patterns/steps_and_stages.md'
        - Auto deploy to dev: 'patterns/auto_deploy_to_dev.md'  
        - HTTP requests from backend: 'patterns/making_http_request_with_request_library.md'  
        - Error Handling in async.auto(): 'patterns/error_handling_asyncauto.md'  
        - Asset Pipeline: 'patterns/asset_pipeline.md'
        - Auto Saving Forms: 'patterns/auto_saving_forms.md'
    - How to:
        - Change Favicon: 'how_to/change_favicon.md'
        - Clear broswer cache: 'how_to/clear_cache_browser.md'
        - Clear cloudflare cache: 'how_to/clear_cache_cloudflare.md'
        - Use blueprint APIs: 'how_to/use_blueprint_apis.md'
        - Inject data into database with collection runner: 'how_to/use_postman_runner_inject_data_into_database.md'
        - Kill something running in a port: 'how_to/kill_something_running_in_a_port.md'
        - Make local server remotely accessible: 'how_to/make_local_server_remotely_accesible.md'
        - Change file upload limit in Nginx: 'how_to/increase_file_upload_limit_nginx.md'
        - Prevent multiple form submissions by using loader on buttons: 'how_to/prevent_multiple_form_submissions_using_loader.md'

    # static_templates:
    #     - 404.html

    # include_search_page: false
    # search_index_only: false

    # highlightjs: true
    # hljs_languages: []
    # hljs_style: github

    # navigation_depth: 2
    # nav_style: primary

    # shortcuts:
    #     help: 191    # ?
    #     next: 78     # n
    #     previous: 80 # p
    #     search: 83   # s

# theme:
#     name: readthedocs
#     nav_style: dark
# theme: 
    # name: alabaster
    # name: readthedocs
    # include_toc: true
    # extra_nav_links:
    #     Fork me on GitHub: https://github.com/iamale/rock-cli
    # show_powered_by: false


# theme:
#     name: null
#     custom_dir: 'custom_theme'
    # theme_dir: 'custom_theme'

# nav:
#     - Home: index.md
#     - User Guide: guide.md
#     - Developer Guide: dev.md
#     - License: license.md

# extra_css:
#     - extra.css

# extra:
#   # logo: logo.png
#   # logo_title: "Rocketbank logo"
#   # include_toc: yes
#   # extra_nav_links:
#     Fork me on GitHub: https://github.com/iamale/rock-cli
#     sidebars:
#         - about
#         - toc
#         # - my-awesome-sidebar # corresponds to `$THEME_DIR/sidebars/my-awesome-sidebar.html`
#         - related
#         - search

markdown_extensions:
  - toc:
      permalink: true
